nguage: node_js
node_js:
- '0.12'
- '0.10'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: bernardotolosajr@gmail.com
  api_key:
    secure: Apk90RGMkDaLj42ydPAAkEUCclFmEAeO2nkyICSzDXVD+Ifw821ywkp7OLp2Vo2DiOfQdGno1y5jLkH+KqfIUTAXjM1SmI+P1YZlXfIEbaSsuxa5kVT6sqoQhIQpN6fkhn0t4XZ855Mr/pBSAlcJjLUOQhVIuv/bnyt6IgdRRAs=
  on:
    tags: true
    repo: BernardTolosajr/globelabs-sms
