language: node_js
node_js:
- '0.12'
- '0.10'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: bernardotolosajr@gmail.com
  api_key:
    secure: XJvxIyeTnE/ISQ8vyJvRl38q4ezCh2Fm1OXz5ZsYVCd/nFmppFjbPMdfqWbrG14lEmaantJ3FylGbEJiH3+DJrptm/DDsGnRRXjeGsMnrDIjpIlcqlTZznxd/Tm65lVI7yWM3GMMboyN0aUjBTjxMOr41PLyIiOXSsclhX14iLQ=
